# This file was generated by GoReleaser. DO NOT EDIT.
cask "harness-sync" do
  version "0.29.14"

  on_macos do
    on_intel do
      sha256 "3189d807480e70952e064cbafa4ba50ed5d80f93cc2df4d30c921cf81622a94f"
      url "https://github.com/lukaszraczylo/harness-sync/releases/download/v#{version}/harness-sync-darwin-amd64.tar.gz"
    end
    on_arm do
      sha256 "e25e2a874491d94247720dace260ce9216a7930f64a6287ce28865ad72ac04f2"
      url "https://github.com/lukaszraczylo/harness-sync/releases/download/v#{version}/harness-sync-darwin-arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "6c5314248e5c21d032bcf14ff0ad0183ee700d1b45c7550e73d5f556cc966855"
      url "https://github.com/lukaszraczylo/harness-sync/releases/download/v#{version}/harness-sync-linux-amd64.tar.gz"
    end
    on_arm do
      sha256 "e166b5ffeb4381190743030f448be0afbe5bb7ca8ef85fa542068df89b70b12a"
      url "https://github.com/lukaszraczylo/harness-sync/releases/download/v#{version}/harness-sync-linux-arm64.tar.gz"
    end
  end

  name "harness-sync"
  desc "Sync skills, agents, MCP, and LLM endpoints across multiple LLM harnesses"
  homepage "https://github.com/lukaszraczylo/harness-sync"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "harness-sync"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}/harness-sync"]
    end
  end

  # No zap stanza required

end
