# This file was generated by GoReleaser. DO NOT EDIT.
cask "harness-sync" do
  version "0.29.12"

  on_macos do
    on_intel do
      sha256 "605008cabc5d996a13af2bcc939cbc07b521b71e30d52de31643b808f7ed37be"
      url "https://github.com/lukaszraczylo/harness-sync/releases/download/v#{version}/harness-sync-darwin-amd64.tar.gz"
    end
    on_arm do
      sha256 "cec19e783af274091648b9695eb33fc87f42ece46bb523858fed89928a436363"
      url "https://github.com/lukaszraczylo/harness-sync/releases/download/v#{version}/harness-sync-darwin-arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "22bba33ac010936b9f61e1a59d40ec4c996a77b92cb2f4371feca9c2aa8469b1"
      url "https://github.com/lukaszraczylo/harness-sync/releases/download/v#{version}/harness-sync-linux-amd64.tar.gz"
    end
    on_arm do
      sha256 "50df45932c8a22ea452e5f1df24abc2efc639a842bb7cdcc9030e862db079d7b"
      url "https://github.com/lukaszraczylo/harness-sync/releases/download/v#{version}/harness-sync-linux-arm64.tar.gz"
    end
  end

  name "harness-sync"
  desc "Sync skills, agents, MCP, and LLM endpoints across multiple LLM harnesses"
  homepage "https://github.com/lukaszraczylo/harness-sync"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "harness-sync"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}/harness-sync"]
    end
  end

  # No zap stanza required

end
