# This file was generated by GoReleaser. DO NOT EDIT.
cask "harness-sync" do
  version "0.31.5"

  on_macos do
    on_arm do
      sha256 "ff8bbb3b99a82c8db8026141313dbb44c9c0ed88ffcb3d0bf88331b5223c9a7f"
      url "https://github.com/lukaszraczylo/harness-sync/releases/download/v#{version}/harness-sync-darwin-arm64.tar.gz"
    end
    on_intel do
      sha256 "27676a70fd9676f4c4d02b118f6f6a7b3aa7ef00368b14c1dd6376e5ac757e49"
      url "https://github.com/lukaszraczylo/harness-sync/releases/download/v#{version}/harness-sync-darwin-amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "a479e6dc299b101b1a3fd860ba263e942e26d5fa69bd74862ee64c64c0c67d32"
      url "https://github.com/lukaszraczylo/harness-sync/releases/download/v#{version}/harness-sync-linux-arm64.tar.gz"
    end
    on_intel do
      sha256 "3fd7da3c43dd4f6f6f2a1a92dc46ae43fca873eabe5c37c8e1d1f40882a2a5cb"
      url "https://github.com/lukaszraczylo/harness-sync/releases/download/v#{version}/harness-sync-linux-amd64.tar.gz"
    end
  end

  name "harness-sync"
  desc "Sync skills, agents, MCP, and LLM endpoints across multiple LLM harnesses"
  homepage "https://github.com/lukaszraczylo/harness-sync"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "harness-sync"

  postflight_steps do
    on_macos do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/harness-sync"]
    end
  end

  # No zap stanza required
end
