# This file was generated by GoReleaser. DO NOT EDIT.
cask "kportal" do
  name "kportal"
  desc "Modern Kubernetes port-forward manager with interactive TUI"
  homepage "https://lukaszraczylo.github.io/kportal"
  version "0.2.57"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kportal"

  on_macos do
    on_intel do
      url "https://github.com/lukaszraczylo/kportal/releases/download/v#{version}/kportal-#{version}-darwin-amd64.tar.gz",
        verified: "github.com/lukaszraczylo/kportal"
      sha256 "96ca745934c45d0695ad02e2d6e47879c9f964519b6f9fd9235f3e4d23723f26"
    end
    on_arm do
      url "https://github.com/lukaszraczylo/kportal/releases/download/v#{version}/kportal-#{version}-darwin-arm64.tar.gz",
        verified: "github.com/lukaszraczylo/kportal"
      sha256 "b40a789ede6a91a675fb7480623ae2f1c60c957a28d2c7849e0e7f32c464e749"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/lukaszraczylo/kportal/releases/download/v#{version}/kportal-#{version}-linux-amd64.tar.gz",
        verified: "github.com/lukaszraczylo/kportal"
      sha256 "39088145553f06d7b2bef963c06379e8b3290b9bcd61e0c4a1c3554267557816"
    end
    on_arm do
      url "https://github.com/lukaszraczylo/kportal/releases/download/v#{version}/kportal-#{version}-linux-arm64.tar.gz",
        verified: "github.com/lukaszraczylo/kportal"
      sha256 "40e72e88f0aab22da512b8c0eb0aa9ed4aa2e79aafa317ba869e14a36afcf04b"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}/kportal"]
    end
  end

  # No zap stanza required
end
