# This file was generated by GoReleaser. DO NOT EDIT.
cask "kportal" do
  name "kportal"
  desc "Modern Kubernetes port-forward manager with interactive TUI"
  homepage "https://lukaszraczylo.github.io/kportal"
  version "0.2.84"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kportal"

  on_macos do
    on_intel do
      url "https://github.com/lukaszraczylo/kportal/releases/download/v#{version}/kportal-#{version}-darwin-amd64.tar.gz",
        verified: "github.com/lukaszraczylo/kportal"
      sha256 "6bbe4223a110befc555392045750abb4e2bccb9863142501d862538fb3406857"
    end
    on_arm do
      url "https://github.com/lukaszraczylo/kportal/releases/download/v#{version}/kportal-#{version}-darwin-arm64.tar.gz",
        verified: "github.com/lukaszraczylo/kportal"
      sha256 "f75fe4b8c7c87e0fabf997887dc15ce88c333a5185cee9b864e5e4f7851d967e"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/lukaszraczylo/kportal/releases/download/v#{version}/kportal-#{version}-linux-amd64.tar.gz",
        verified: "github.com/lukaszraczylo/kportal"
      sha256 "6154cf30c34a4cdd6160f1c91dc970f4f4c88d5993102aa898d4c821eeaf90c0"
    end
    on_arm do
      url "https://github.com/lukaszraczylo/kportal/releases/download/v#{version}/kportal-#{version}-linux-arm64.tar.gz",
        verified: "github.com/lukaszraczylo/kportal"
      sha256 "6c09e76c892054fa3119dfd42d6fa8c6cbc03665bddf52c2b5f780145d82da95"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}/kportal"]
    end
  end

  # No zap stanza required
end
