# This file was generated by GoReleaser. DO NOT EDIT.
cask "kportal" do
  name "kportal"
  desc "Modern Kubernetes port-forward manager with interactive TUI"
  homepage "https://lukaszraczylo.github.io/kportal"
  version "0.2.72"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kportal"

  on_macos do
    on_intel do
      url "https://github.com/lukaszraczylo/kportal/releases/download/v#{version}/kportal-#{version}-darwin-amd64.tar.gz",
        verified: "github.com/lukaszraczylo/kportal"
      sha256 "49f35db4dec7b75cfc5b623d77d45f65c1682cc42c1a2c93fe9486c1d22d09fa"
    end
    on_arm do
      url "https://github.com/lukaszraczylo/kportal/releases/download/v#{version}/kportal-#{version}-darwin-arm64.tar.gz",
        verified: "github.com/lukaszraczylo/kportal"
      sha256 "f8bd127b523aaf6ff4074f77661c267b3b2e4f1def7eba118a3ce16fc347bebd"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/lukaszraczylo/kportal/releases/download/v#{version}/kportal-#{version}-linux-amd64.tar.gz",
        verified: "github.com/lukaszraczylo/kportal"
      sha256 "e9a2ec157e9fb76c0b4becf1f068596e3bb2a92333cead71541535614cce8c38"
    end
    on_arm do
      url "https://github.com/lukaszraczylo/kportal/releases/download/v#{version}/kportal-#{version}-linux-arm64.tar.gz",
        verified: "github.com/lukaszraczylo/kportal"
      sha256 "86473480e4af8cb726a38d2a5b7f28a83126faf9ced25701767823f64d8bae37"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}/kportal"]
    end
  end

  # No zap stanza required
end
