# This file was generated by GoReleaser. DO NOT EDIT.
cask "lolcathost" do
  version "0.2.17"

  on_macos do
    on_arm do
      sha256 "0d52b836febc682bc93fb0c85505bb046755991e464de80c2aacc9f2ed2899fa"
      url "https://github.com/lukaszraczylo/lolcathost/releases/download/v#{version}/lolcathost-#{version}-darwin-arm64.tar.gz"
    end
    on_intel do
      sha256 "e2e5601ae792b0eca7713581b6406282a5038592770d4690ec91cfe7d98c03ed"
      url "https://github.com/lukaszraczylo/lolcathost/releases/download/v#{version}/lolcathost-#{version}-darwin-amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "5e50fed0c5d178428cc8bb76a523a755958a4db116152e75a040139678d1e5df"
      url "https://github.com/lukaszraczylo/lolcathost/releases/download/v#{version}/lolcathost-#{version}-linux-arm64.tar.gz"
    end
    on_intel do
      sha256 "ded86e59770c3bfefd207dcefb5aafd3cc807cc3e9396c68b2bb51e3721c56b0"
      url "https://github.com/lukaszraczylo/lolcathost/releases/download/v#{version}/lolcathost-#{version}-linux-amd64.tar.gz"
    end
  end

  name "lolcathost"
  desc "Dynamic host management tool with TUI"
  homepage "https://github.com/lukaszraczylo/lolcathost"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "lolcathost"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}/lolcathost"]
    end
  end

  # No zap stanza required
end
