# This file was generated by GoReleaser. DO NOT EDIT.
cask "lolcathost" do
  name "lolcathost"
  desc "Dynamic host management tool with TUI"
  homepage "https://github.com/lukaszraczylo/lolcathost"
  version "0.1.33"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "lolcathost"

  on_macos do
    on_intel do
      url "https://github.com/lukaszraczylo/lolcathost/releases/download/v#{version}/lolcathost-#{version}-darwin-amd64.tar.gz"
      sha256 "a702a00dcf9d783a73dd786cde6b3fba7b1f18569277907b26932c093093cd46"
    end
    on_arm do
      url "https://github.com/lukaszraczylo/lolcathost/releases/download/v#{version}/lolcathost-#{version}-darwin-arm64.tar.gz"
      sha256 "4d404a08405761886fd9c8d9fec6af471ad0037b52bb18e354f7122bc10b2b17"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/lukaszraczylo/lolcathost/releases/download/v#{version}/lolcathost-#{version}-linux-amd64.tar.gz"
      sha256 "7778b69f60e58c0bd0db4c207ccc9454dda9072cc3cbe0ef4bc23901505deeef"
    end
    on_arm do
      url "https://github.com/lukaszraczylo/lolcathost/releases/download/v#{version}/lolcathost-#{version}-linux-arm64.tar.gz"
      sha256 "45a797a614d37b5427fbe2cad22a3d33e49c5c62ced77925868b073967015dfc"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}/lolcathost"]
    end
  end

  # No zap stanza required
end
