# This file was generated by GoReleaser. DO NOT EDIT.
cask "lolcathost" do
  name "lolcathost"
  desc "Dynamic host management tool with TUI"
  homepage "https://github.com/lukaszraczylo/lolcathost"
  version "0.1.46"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "lolcathost"

  on_macos do
    on_intel do
      url "https://github.com/lukaszraczylo/lolcathost/releases/download/v#{version}/lolcathost-#{version}-darwin-amd64.tar.gz"
      sha256 "87ff29780be6df60414648c901fb26a1b085b948c4f90d2ff14c6fdf2ab807a8"
    end
    on_arm do
      url "https://github.com/lukaszraczylo/lolcathost/releases/download/v#{version}/lolcathost-#{version}-darwin-arm64.tar.gz"
      sha256 "9ce8f6eef3c56705f92c7fea8afcc98847d2b84e2e1889dc79b1f9d159ab4ebc"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/lukaszraczylo/lolcathost/releases/download/v#{version}/lolcathost-#{version}-linux-amd64.tar.gz"
      sha256 "3dd353043405f8b695fb082679d059330f4e22fee39b9e42eccfe77182c117cb"
    end
    on_arm do
      url "https://github.com/lukaszraczylo/lolcathost/releases/download/v#{version}/lolcathost-#{version}-linux-arm64.tar.gz"
      sha256 "899cedf173c6b5a8b7bedfa113c2bcf6240f8c406a7143026281e3947695f167"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}/lolcathost"]
    end
  end

  # No zap stanza required
end
