# This file was generated by GoReleaser. DO NOT EDIT.
cask "mcp-filepuff" do
  version "2.1.8"

  on_macos do
    on_arm do
      sha256 "e7d7e12830258012e7f755f7f8746006809b91a97f4bebd957cb93ea01486df3"
      url "https://github.com/lukaszraczylo/filepuff-mcp/releases/download/v#{version}/mcp-filepuff_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "9bbe8d01fc0a190e3fdf08420f62d1f93b1fb2857d9156684689a22794366dbc"
      url "https://github.com/lukaszraczylo/filepuff-mcp/releases/download/v#{version}/mcp-filepuff_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "49845c635f297b8d3eefa9a2d41c51a74a97757ec522e85f94346fa970052631"
      url "https://github.com/lukaszraczylo/filepuff-mcp/releases/download/v#{version}/mcp-filepuff_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "d8130b97ec92a3a16fc9d0b88749a6a62783958df93b9acea64e4f41386b59ea"
      url "https://github.com/lukaszraczylo/filepuff-mcp/releases/download/v#{version}/mcp-filepuff_#{version}_linux_amd64.tar.gz"
    end
  end

  name "mcp-filepuff"
  desc "AST-aware file operations and LSP integration MCP server for Claude Code"
  homepage "https://github.com/lukaszraczylo/filepuff-mcp"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mcp-filepuff"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}/mcp-filepuff"]
    end
  end

  # No zap stanza required
end
