# This file was generated by GoReleaser. DO NOT EDIT.
cask "readitall" do
  version "0.1.22"

  on_macos do
    on_arm do
      sha256 "32fa5e9fda7f3286aaf75daa39bbc1b63d00cf548591efd22cdc8ec35460919d"
      url "https://github.com/lukaszraczylo/mcp-readitall/releases/download/v#{version}/readitall-#{version}-darwin-arm64.tar.gz"
    end
    on_intel do
      sha256 "611067f3b1d617f98ce154135d884fcfdb53bf75d3294a12fd425a81e38ac21f"
      url "https://github.com/lukaszraczylo/mcp-readitall/releases/download/v#{version}/readitall-#{version}-darwin-amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "7632056ab2d0bcb2115b1d6f4d773d1d41b8801c351b64d368649d234085fb75"
      url "https://github.com/lukaszraczylo/mcp-readitall/releases/download/v#{version}/readitall-#{version}-linux-arm64.tar.gz"
    end
    on_intel do
      sha256 "9d352d9e4db028f500467d6b7102e8250069fded6ebc8bb9bd70cc028a62354a"
      url "https://github.com/lukaszraczylo/mcp-readitall/releases/download/v#{version}/readitall-#{version}-linux-amd64.tar.gz"
    end
  end

  name "readitall"
  desc "MCP server that reads web pages through a headless Chromium-family browser"
  homepage "https://github.com/lukaszraczylo/mcp-readitall"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "readitall"

  postflight_steps do
    on_macos do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/readitall"]
    end
  end

  # No zap stanza required
end
