# This file was generated by GoReleaser. DO NOT EDIT.
cask "readitall" do
  version "0.1.18"

  on_macos do
    on_arm do
      sha256 "e89895c13d35046d3612681fed78fe51f17759a60ad0ed1c564ca60e29c4a0d0"
      url "https://github.com/lukaszraczylo/mcp-readitall/releases/download/v#{version}/readitall-#{version}-darwin-arm64.tar.gz"
    end
    on_intel do
      sha256 "7447601518496b86b0e870138b0aa5140b8831251b512c644f2ea85eb98d55d3"
      url "https://github.com/lukaszraczylo/mcp-readitall/releases/download/v#{version}/readitall-#{version}-darwin-amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "074f3bfe299d40eee86682e6e5af050f769a1100839e0f9460839a26e11c9fa5"
      url "https://github.com/lukaszraczylo/mcp-readitall/releases/download/v#{version}/readitall-#{version}-linux-arm64.tar.gz"
    end
    on_intel do
      sha256 "7caead01a1828473ce3994837c4c9544936eb1ee2d4d7cf03a8d65faed18079b"
      url "https://github.com/lukaszraczylo/mcp-readitall/releases/download/v#{version}/readitall-#{version}-linux-amd64.tar.gz"
    end
  end

  name "readitall"
  desc "MCP server that reads web pages through a headless Chromium-family browser"
  homepage "https://github.com/lukaszraczylo/mcp-readitall"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "readitall"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}/readitall"]
    end
  end

  # No zap stanza required
end
