# This file was generated by GoReleaser. DO NOT EDIT.
cask "readitall" do
  version "0.1.20"

  on_macos do
    on_arm do
      sha256 "c2128622e4a335f02dd1fd966d93c4550f24dc8ff7ab5c3ba4579d150edbdc12"
      url "https://github.com/lukaszraczylo/mcp-readitall/releases/download/v#{version}/readitall-#{version}-darwin-arm64.tar.gz"
    end
    on_intel do
      sha256 "cf94da8b01e941c5abbff6112b0ab826df5f690ded342e2a47b0fe90387ae558"
      url "https://github.com/lukaszraczylo/mcp-readitall/releases/download/v#{version}/readitall-#{version}-darwin-amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "0f434df875a9add55b677bcf701d74ecef0157068f40ba368c8a56ccdf677bf9"
      url "https://github.com/lukaszraczylo/mcp-readitall/releases/download/v#{version}/readitall-#{version}-linux-arm64.tar.gz"
    end
    on_intel do
      sha256 "a2886fec390a347acdd90079f1fc1b123734674af175d9a1473418175efc6799"
      url "https://github.com/lukaszraczylo/mcp-readitall/releases/download/v#{version}/readitall-#{version}-linux-amd64.tar.gz"
    end
  end

  name "readitall"
  desc "MCP server that reads web pages through a headless Chromium-family browser"
  homepage "https://github.com/lukaszraczylo/mcp-readitall"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "readitall"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}/readitall"]
    end
  end

  # No zap stanza required
end
