# This file was generated by GoReleaser. DO NOT EDIT.
cask "semver-generator" do
  name "semver-generator"
  desc "Automatic semantic version generator based on git commit messages"
  homepage "https://github.com/lukaszraczylo/semver-generator"
  version "1.16.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "semver-generator"

  on_macos do
    on_intel do
      url "https://github.com/lukaszraczylo/semver-generator/releases/download/v#{version}/semver-generator-darwin-amd64.tar.gz"
      sha256 "4d8da33ddd5f1c02e1568ea435ea1c9610e6c56d45e7eb5b08465f046f420b67"
    end
    on_arm do
      url "https://github.com/lukaszraczylo/semver-generator/releases/download/v#{version}/semver-generator-darwin-arm64.tar.gz"
      sha256 "42004bf99e9b9c202a4568d7ca57f8b53f3ad9f5d9672bb50483d511e4168544"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/lukaszraczylo/semver-generator/releases/download/v#{version}/semver-generator-linux-amd64.tar.gz"
      sha256 "567b615860925fb351ea89bb5e3af070d943f8c207d468c73a9ff6dab0c9945b"
    end
    on_arm do
      url "https://github.com/lukaszraczylo/semver-generator/releases/download/v#{version}/semver-generator-linux-arm64.tar.gz"
      sha256 "733cf86828337ce176b0cdd6228c28d0369a5811e905f2271013959e3e4e8ea1"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}/semver-generator"]
    end
  end

  # No zap stanza required
end
