# This file was generated by GoReleaser. DO NOT EDIT.
cask "semver-generator" do
  name "semver-generator"
  desc "Automatic semantic version generator based on git commit messages"
  homepage "https://github.com/lukaszraczylo/semver-generator"
  version "1.16.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "semver-generator"

  on_macos do
    on_intel do
      url "https://github.com/lukaszraczylo/semver-generator/releases/download/v#{version}/semver-generator-darwin-amd64.tar.gz"
      sha256 "4a774527c9c9a458b93014169a79360233caa565164f5a0e8eac5c08aa11349e"
    end
    on_arm do
      url "https://github.com/lukaszraczylo/semver-generator/releases/download/v#{version}/semver-generator-darwin-arm64.tar.gz"
      sha256 "cd75204eac0bf881d670eeefcfdf5705e8dc1167eb7a53cbdaab6a0f77a82c9b"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/lukaszraczylo/semver-generator/releases/download/v#{version}/semver-generator-linux-amd64.tar.gz"
      sha256 "c3536cb71e865a839e399a98697af9dfdd57576f45d7ffaa53d3c791606c1eba"
    end
    on_arm do
      url "https://github.com/lukaszraczylo/semver-generator/releases/download/v#{version}/semver-generator-linux-arm64.tar.gz"
      sha256 "f65b3377027af9c9918ae347a1c9d655e9a879309b7b43c7e929166be3b53690"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}/semver-generator"]
    end
  end

  # No zap stanza required
end
