# This file was generated by GoReleaser. DO NOT EDIT.
cask "semver-generator" do
  version "1.18.15"

  on_macos do
    on_arm do
      sha256 "8b51ff689be874fbb88868c7371a1aadae876520bbf42e4c5483c8f5f07b7690"
      url "https://github.com/lukaszraczylo/semver-generator/releases/download/v#{version}/semver-generator-darwin-arm64.tar.gz"
    end
    on_intel do
      sha256 "1c3351959a97078b6afeceb6f589a980c375624757a5b0cc3bbd7d010a68b352"
      url "https://github.com/lukaszraczylo/semver-generator/releases/download/v#{version}/semver-generator-darwin-amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "65bf2b7e01a5ef568425cb6a5cd1bce2b8d709c8092d958e947db40dfcacf089"
      url "https://github.com/lukaszraczylo/semver-generator/releases/download/v#{version}/semver-generator-linux-arm64.tar.gz"
    end
    on_intel do
      sha256 "d9d5201e12705e684992762c32a39ee886a491a26f57b1c1b0ede7152d13affe"
      url "https://github.com/lukaszraczylo/semver-generator/releases/download/v#{version}/semver-generator-linux-amd64.tar.gz"
    end
  end

  name "semver-generator"
  desc "Automatic semantic version generator based on git commit messages"
  homepage "https://github.com/lukaszraczylo/semver-generator"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "semver-generator"

  postflight_steps do
    on_macos do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/semver-generator"]
    end
  end

  # No zap stanza required
end
