# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kportal < Formula
  desc "Modern Kubernetes port-forward manager with interactive TUI"
  homepage "https://lukaszraczylo.github.io/kportal"
  version "0.2.20"
  license "MIT"

  depends_on "kubernetes-cli" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/lukaszraczylo/kportal/releases/download/v0.2.20/kportal-0.2.20-darwin-amd64.tar.gz"
      sha256 "3c3d54d432340b5a7d279e67979f5df8009b7d1889b3a78a2128c90a6022a523"

      def install
        bin.install "kportal"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/lukaszraczylo/kportal/releases/download/v0.2.20/kportal-0.2.20-darwin-arm64.tar.gz"
      sha256 "47ca19354fcc7b03cac89fc8d9ca7f7a9fd27abe36637977eddc4b7970dffaa3"

      def install
        bin.install "kportal"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/lukaszraczylo/kportal/releases/download/v0.2.20/kportal-0.2.20-linux-amd64.tar.gz"
      sha256 "f5aac1a37add67b716094c7390333cc6ad1785ecd9ae8663f33ed855fca6046f"
      def install
        bin.install "kportal"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/lukaszraczylo/kportal/releases/download/v0.2.20/kportal-0.2.20-linux-arm64.tar.gz"
      sha256 "58cfae272d02584028aded06f97483c60a916d0e1c22577aa8b8902342aa9c4e"
      def install
        bin.install "kportal"
      end
    end
  end

  test do
    system "#{bin}/kportal", "--version"
  end
end
