# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kportal < Formula
  desc "Modern Kubernetes port-forward manager with interactive TUI"
  homepage "https://lukaszraczylo.github.io/kportal"
  version "0.2.24"
  license "MIT"

  depends_on "kubernetes-cli" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/lukaszraczylo/kportal/releases/download/v0.2.24/kportal-0.2.24-darwin-amd64.tar.gz"
      sha256 "a9cb44f0881ffedfc9c48706268c165b748b4fa93a077a4869c988b7da143c95"

      def install
        bin.install "kportal"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/lukaszraczylo/kportal/releases/download/v0.2.24/kportal-0.2.24-darwin-arm64.tar.gz"
      sha256 "c9819d9b7a4566085d0c67145af84cb3ff72651f19574d1cc21516d9dbe0baea"

      def install
        bin.install "kportal"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/lukaszraczylo/kportal/releases/download/v0.2.24/kportal-0.2.24-linux-amd64.tar.gz"
      sha256 "f23f68ffdcffe747f021ae2b051c9510eb0f94e2f4a1a42758b60208f3f482d9"
      def install
        bin.install "kportal"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/lukaszraczylo/kportal/releases/download/v0.2.24/kportal-0.2.24-linux-arm64.tar.gz"
      sha256 "ed133d7ada0a41927be9a3a4d9a2365495f97ee0fb7876d371f6ebc200572ab9"
      def install
        bin.install "kportal"
      end
    end
  end

  test do
    system "#{bin}/kportal", "--version"
  end
end
