# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lolcathost < Formula
  desc "Dynamic host management tool for macOS and Linux with TUI"
  homepage "https://github.com/lukaszraczylo/lolcathost"
  version "0.1.8"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/lukaszraczylo/lolcathost/releases/download/v0.1.8/lolcathost-0.1.8-darwin-amd64.tar.gz"
      sha256 "cc8bc6475725ed309a97b865a7937019d0036d33fa40fb31443195a912a98444"

      def install
        bin.install "lolcathost"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/lukaszraczylo/lolcathost/releases/download/v0.1.8/lolcathost-0.1.8-darwin-arm64.tar.gz"
      sha256 "ac9547f967b9c006995ecbd730237cd9c9d5fb59a45913d90ecc90f1a777a673"

      def install
        bin.install "lolcathost"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/lukaszraczylo/lolcathost/releases/download/v0.1.8/lolcathost-0.1.8-linux-amd64.tar.gz"
      sha256 "c90b209cca77c254318887bcfc7ae13919062c4634d1fb93a2f14b7101d9f92e"
      def install
        bin.install "lolcathost"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/lukaszraczylo/lolcathost/releases/download/v0.1.8/lolcathost-0.1.8-linux-arm64.tar.gz"
      sha256 "dd5630a1b3f5a53957fcc706c9e8d4e373d02818f8389c0442a9042047eb96c0"
      def install
        bin.install "lolcathost"
      end
    end
  end

  test do
    system "#{bin}/lolcathost", "--version"
  end
end
